"""add a mail list

Revision ID: 51d7fc3ee93c
Revises: fe9629bc339d
Create Date: 2020-05-11 14:05:59.376091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d7fc3ee93c'
down_revision = 'fe9629bc339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maillist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maillist')
    # ### end Alembic commands ###
